name: GitHub Pages

on:
  push:
    branches:
      - v2
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build Pages
    runs-on: ubuntu-latest
    steps:
      - name: Initialize repository
        uses: actions/checkout@v4
        with:
          ref: v2
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          pip-install: -r requirements-build.txt
      - name: Cache CANN
        id: cache-cann
        uses: actions/cache@v5
        with:
          path: cann.run
          key: cann_9.0.0-beta.2_linux-x86_64
      - name: Download CANN
        if: steps.cache-cann.outputs.cache-hit != 'true'
        run: |
          wget -qO cann.run https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/CANN/CANN%209.0.T511/Ascend-cann_9.0.0-beta.2_linux-x86_64.run
      - name: Install CANN
        run: |
          printf 'y\ny\n2\n' | bash cann.run --full
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v5
        with:
          path: llvm
          key: llvm-86b69c31-ubuntu-x64
      - name: Download LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          mkdir llvm
          cd llvm
          wget -qO llvm.tgz https://oaitriton.blob.core.windows.net/public/llvm-builds/llvm-86b69c31-ubuntu-x64.tar.gz
          tar xf llvm.tgz --strip-components 1
          rm llvm.tgz
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Sphinx
        env:
          LLVM_INSTALL_PREFIX: llvm
          PYASC_SETUP_DOCS: 1
        run: |
          python3 -m pip install -e ".[docs]" -v
          source ~/Ascend/cann/set_env.sh
          cd docs
          make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

  deploy:
    name: Deploy Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
